angular.module('pu.workflow',
    [
        'pu.workflow.services',
        'pu.workflow.filters',
        'pu.workflow.controllers'
    ]);
angular.module('pu.workflow.services',[]);
angular.module('pu.workflow.filters',[])
angular.module('pu.workflow.controllers',[]);
